#_BASE_: Fast-COCO-InstanceSegmentation.yaml
_BASE_: Fast-COCO-InstanceSegmentation_for6gpu.yaml
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd_backbone"
  WEIGHTS: "checkpoints/resnet50d_ra2-464e36ba.pkl"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  RESNETS:
    DEPTH: 50
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: [ "res3", "res4", "res5" ]
    DEFORM_ON_PER_STAGE: [ False, False, True, True ] # dcn on res4, res5
  META_ARCHITECTURE: "FastInst"
  SEM_SEG_HEAD:
    NAME: "FastInstHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 80
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "PyramidPoolingModuleFPN"
    IN_FEATURES: [ "res3", "res4", "res5" ]
  FASTINST:
    TRANSFORMER_DECODER_NAME: "FastInstDecoder"
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    LOCATION_WEIGHT: 1000.0
    PROPOSAL_WEIGHT: 20.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NUM_AUX_QUERIES: 8
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 1024
    PRE_NORM: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 3
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
#  IMS_PER_BATCH: 16  # 4GPU
#  BASE_LR: 0.0001
#  STEPS: (327778, 355092)
  WARMUP_FACTOR: 1.0
#  MAX_ITER: 368750  # 50 * 7375 = 368750
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  #  CLIP_GRADIENTS:
  #    ENABLED: True
  #    CLIP_TYPE: "full_model"
  #    CLIP_VALUE: 0.01
  #    NORM_TYPE: 2.0
  AMP:
    ENABLED: False
#    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 853
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 853
  CROP:
    ENABLED: True
    RESIZE:
      ENABLED: True
      MIN_SIZE: (400, 500, 600)
      MIN_SIZE_TRAIN_SAMPLING: "choice"
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "fastinst_instance"
#TEST:
#  EVAL_PERIOD: 5000
#  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4 # 原始
VERSION: 2
SEED: 42
OUTPUT_DIR: "output/fastinst_r50-vd-dcn_ppm-fpn_bs16_50ep_x3_640_6gpu_foregroud-2(1-f)^2_backgroud-1"

REWEIGHT:
  # ALPHA_REWEIGHT: 10.0
  ALPHA_REWEIGHT: 2.0